apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2jenk
  labels:
    app: tp2jenk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp2jenk
  template:
    metadata:
      labels:
        app: tp2jenk
    spec:
      containers:
        - name: tp2jenk
          image: 192.168.122.1:5001/tp2jenk
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: nexus-docker
